// import { StaffDetail } from './staff.model';

// export const STAFF_MOCKS: StaffDetail[] = [
//     {
//         address: '1133/16 Đường 3 tháng 2, P6, Quận 11',
//         birthDate: '01/07/1998',
//         country: 'Vietnam',
//         dateActivated: '20/03/2020',
//         fullName: 'FIRST_NAME',
//         email: 'mock@gmail.com',
//         gender: 1,
//         id: '1',
//         lastName: 'LAST_NAME',
//         nationality: 'Vietnamese',
//         phoneNumber: '0900099999',
//         province: '700000',
//         checked: false,
//     },
//     {
//         address: '1133/16 Đường 3 tháng 2, P6, Quận 11',
//         birthDate: '01/07/1998',
//         country: 'Vietnam',
//         dateActivated: '20/03/2020',
//         fullName: 'FIRST_NAME',
//         email: 'mock@gmail.com',
//         gender: 1,
//         id: '1',
//         lastName: 'LAST_NAME',
//         nationality: 'Vietnamese',
//         phoneNumber: '0900099999',
//         province: '700000',
//         checked: false,

//     },
//     {
//         address: '1133/16 Đường 3 tháng 2, P6, Quận 11',
//         birthDate: '01/07/1998',
//         country: 'Vietnam',
//         dateActivated: '20/03/2020',
//         fullName: 'FIRST_NAME',
//         email: 'mock@gmail.com',
//         gender: 1,
//         id: '1',
//         lastName: 'LAST_NAME',
//         nationality: 'Vietnamese',
//         phoneNumber: '0900099999',
//         province: '700000',
//         checked: false,

//     },
//     {
//         address: '1133/16 Đường 3 tháng 2, P6, Quận 11',
//         birthDate: '01/07/1998',
//         country: 'Vietnam',
//         dateActivated: '20/03/2020',
//         fullName: 'FIRST_NAME',
//         email: 'mock@gmail.com',
//         gender: 1,
//         id: '1',
//         lastName: 'LAST_NAME',
//         nationality: 'Vietnamese',
//         phoneNumber: '0900099999',
//         province: '700000',
//         checked: false,

//     },
//     {
//         address: '1133/16 Đường 3 tháng 2, P6, Quận 11',
//         birthDate: '01/07/1998',
//         country: 'Vietnam',
//         dateActivated: '20/03/2020',
//         fullName: 'FIRST_NAME',
//         email: 'mock@gmail.com',
//         gender: 1,
//         id: '1',
//         lastName: 'LAST_NAME',
//         nationality: 'Vietnamese',
//         phoneNumber: '0900099999',
//         province: '700000',
//         checked: false,

//     },
//     {
//         address: '1133/16 Đường 3 tháng 2, P6, Quận 11',
//         birthDate: '01/07/1998',
//         country: 'Vietnam',
//         dateActivated: '20/03/2020',
//         fullName: 'FIRST_NAME',
//         email: 'mock@gmail.com',
//         gender: 1,
//         id: '1',
//         lastName: 'LAST_NAME',
//         nationality: 'Vietnamese',
//         phoneNumber: '0900099999',
//         province: '700000',
//         checked: false,

//     },
//     {
//         address: '1133/16 Đường 3 tháng 2, P6, Quận 11',
//         birthDate: '01/07/1998',
//         country: 'Vietnam',
//         dateActivated: '20/03/2020',
//         fullName: 'FIRST_NAME',
//         email: 'mock@gmail.com',
//         gender: 1,
//         id: '1',
//         lastName: 'LAST_NAME',
//         nationality: 'Vietnamese',
//         phoneNumber: '0900099999',
//         province: '700000',
//         checked: false,

//     },
// ];



